### ISSUE TITLE
Multi-highlighter nesting

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#111]
Currently highlighters are nested, so for instance in the HTML highlighter with scripts, there are sub-sections for CSS and JS, but since scripts can exist in those (php, dws...), you would need to have a sub-highlighter for them (CSS with scripts, Javascript with scripts), which results in the script highlighter being replicated multiple times.

Also the non-scripted highlighters are replicated, f.i. you need an "HTML with PHP" and "HTML with DWS", and then you may have a "CSS with PHP", "CSS with DWS", "CSS with SASS", "CSS with LESS", "CSS with SASS and PHP", etc. 

Would it be possible to have an "HTML.json", that would contain just the HTML rules, be usable in multiple flavors of "HTML with scripts", so that only the inclusion rules, need to be specified? basically some form of inheritence or derivation, so HTML with scripts would be

    Base: "HTML.json"
    SubRules : {
        ...there you specify the tokens and sub-highlighters...
    }

The SubRules of the derived highlighter would have highest priority (and basically override the rules of the base). The idea would be that the derived highlighter would contain no keyword list or other details.

**Comment by bonecode** [comment]
Quite hard to implement because scripts are included in various parts of the base script. Basically the whole JSON imported should be written again to make this work. These multi-highlighters are very rare and I have so much other things in my todolist that I must skip this. But if somebody has time to implement this, good luck. :)
