### ISSUE TITLE
Make TBCEditorUndoItem virtual and remove TBCEditorChangeReason

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#122]
Longer term issue, the goal would be to be able to handle higher-level, custom undo actions.

For instance "comment block" or "surround with" actions can modify a lot of lines and can be made codefolding-aware, but if you have to go through several items with TBCEditorChangeReason, it result in a complex undo block that is not codefolding-aware.

This would also naturally break down the monolithic TBCBaseEditor.UndoItem method into many small and simple independent methods.

**Comment by bonecode** [comment]
The problem with the undo and code folding is the code folding rescan. After rescan you lose the pointer to a certain fold range. That's why the UndoItem procedure will uncollapse folds. But basically anything can happen around the code folding and the undo should some how track those changes... blaah... any ideas? :)

I'm not sure if I am at the same page with this TBCEditorChangeReason removing and making TBCEditorUndoItem virtual. If the TBCEditorChangeReason is removed then how did you think that the undo event would know what it should do? Some kind of general action method as a parameter?

**Comment by EricGrange** [comment]
My best idea so far is to get all the code into a single array/tstrings, and have the whole code editing and undo work against that. Only the rendering portion would be code-folding aware.
This way undo (and other stuff) would be dealing in terms of actual/unfolded line numbers, which are more stable.

As for the Undo, it would be performed by a virtual method, so instead of something like

    procedure Editor.UndoItem;
       case reason of
           reason1 : ...undo for reason 1...
           reason2 : ...undo for reason 2...

you would have something like

    procedure Editor.UndoItem;
        reason.Undo

    procedure Reason1.Undo;
       ...undo for reason 1...

    procedure Reason2.Undo;
       ...undo for reason 2...

**Comment by bonecode** [comment]
Actually now I remember that the rescan does not remove collapsed folds...

**Comment by bonecode** [comment]
I think currently undo/redo handling in the single point is better than handling it here and there. I put this on my todolist and maybe some day I don't think it's better anymore. :)

**Comment by EricGrange** [comment]
But with a single point it's quite inflexible, and f.i. there is no way to perform an undo for more complex actions, like a Rename refactor, a block indent or a "Surround with" (at least not without thrashing the code folding AFAICT).
