### ISSUE TITLE
HEREDOC for PHP highlighter

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#192]
Please take a look on this:
http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc

**Comment by bonecode** [comment]
Yes, I am aware of the heredoc. What do you have in mind? 

The heredoc starts with the <<< operator and an identifier. That arbitrary identifier is a bit of problem.

**Comment by noname00-pas** [comment]
@bonecode 
printf(<<<TEST
	THIS IS A VALID HEREDOC
);
TEST


);

**Comment by bonecode** [comment]
Are you sure that is correct?

**Comment by noname00-pas** [comment]
@bonecode Yes, I am. It is correct. After thinking about this issue, It is better if you contact KrystianBigaj (The owner of synweb project - https://github.com/KrystianBigaj/synweb) for the PHP highlighter.

**Comment by bonecode** [comment]
I know synweb very well because I used it in my editor for many years. It's pretty much a dead project now - last update 4 years ago. It is also based on SynEdit highlighters which are components. Components have some advantages but I am not interested in that kind of solution. 

I think I skip the heredoc so far. I tested a few editors and some of them are just highlighting identifier pairs. I added this on my todolist with a low priority.
