### ISSUE TITLE
Drawing & sync edit issues

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#302]
Hi Lasse,
Please see this video:
![2016-01-27_08-51-01](https://cloud.githubusercontent.com/assets/7973218/12601443/aa599eba-c4d3-11e5-96c8-b2428998d0ea.gif)

**Comment by bonecode** [comment]
Ok, thanks. 

There seems to be an issue with the word wrap paint. And I think sync edit should not be allowed when the word wrap is enabled or it should disable/enable it.

That last sync edit issue is not supported yet. Sync edit will change the whole document. I know Delphi has this sync edit feature where you first select a block where you want to make changes and then you choose the word. It could be possible to do so that the first Ctrl+Shit+J will lock the block, if it isn't a word, and then you can select the word and sync edit with the second Ctrl+Shift+J. Multi-caret feature will cover this, I think. Well, let see what happens. :)

**Comment by bonecode** [comment]
Fixed bugs. I will put that selected block sync edit into my todolist.
