### ISSUE TITLE
Colors bug

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#430]
I just changed FontName value to Fixedsys in Default.json:
     "Fonts": {
            "LineNumbers": "Courier New",
            "Text": "**Fixedsys**",

and got this:

![bandicam_2016-07-27_11-05-17-209](https://cloud.githubusercontent.com/assets/11677236/17168351/aabf2cac-53ea-11e6-8680-9d3982250e6d.gif)

**Comment by bonecode** [comment]
Do you have the latest trunk source? I can't repeat that but if I am using other highlighters there is same kind of issue:

![image](https://cloud.githubusercontent.com/assets/11475177/17172781/a71041a8-53ff-11e6-9e6c-ba7a89557b78.png)

Btw. use SpecialChars.Visible = True. It is easier to see what the actual problem is.

**Comment by piker00** [comment]
No, sorry. but now Yes, and I see only this:
![bandicam_2016-07-27_14-03-59-952](https://cloud.githubusercontent.com/assets/11677236/17173420/76cb20fe-5403-11e6-9495-d5284077c37b.gif)

**Comment by piker00** [comment]
Yes, and all this you can see if Syntax is set to text.json if you change syntax you will see only this:
![bandicam_2016-07-27_14-03-59-952](https://cloud.githubusercontent.com/assets/11677236/17173504/eaa866e4-5403-11e6-84f4-4d3a848f4634.gif)

**Comment by piker00** [comment]
With use SpecialChars.Visible = True every thing works perfect, except that some text looks badly
![1](https://cloud.githubusercontent.com/assets/11677236/17173650/bd409356-5404-11e6-8395-40601c7550fe.png)

**Comment by bonecode** [comment]
Fixed.
