### ISSUE TITLE
About demo

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#505]
I think will be better to keep demo with ehLibObjetInspector also + compiled version.
Current demo inspector full S**t.

**Comment by bonecode** [comment]
Why? I think it works quite ok or is it? At least AlphaSkins can skin scrollbar. It is not even close to perfect, I know. But what is, if you don't make it by yourself. :)

**Comment by piker00** [comment]
So then you must fix some property editors like: Color, FontCharset, Cursor, Bitmaps, and may be some others.
In current demo they are Off

**Comment by bonecode** [comment]
Well, those don't matter much. It's just a demo. I think it shows the control possibilities more than enough. But of course, if there is better free alternative for current inspector, I can change it. 

File size also matters because my server has a limit and it goes very close to the top of it every month. With EhLib, the file size was 3 MB bigger (unzipped). I can't also release too many version of EditBone per month. But I have already another server which has 100 GB monthly limit and I will change to it someday.

**Comment by piker00** [comment]
Why you don't use github for release repository?
Do you need downloads counter?
