### ISSUE TITLE
JSONImporters callbacks

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#52]
Currently JSONImporter in JSONImport range invokes TJsonObject.ParseFromFile directly with an hard-coded path.

This is a request to use TJsonBaseObject.ParseFromStream instead and obtain the stream through callback. This would allow to use custom paths as well as obtain the json from executable resources, database or any other means.

It would be okay (for me) to have a global callback, whose default behavior would be to load from the hard-coded path. Ideal would be to have that callback exposed at the TBCEditor level.

**Comment by bonecode** [comment]
Perhaps I need to explain what that range ParseFromFile is all about. It makes possible to include multiple highlighters into a highlighter. See for example "HTML with Scripts.json" and search "IncludeRange". 

I have totally forgotten the hard-coded path since I was testing this feature. Well, it would be easy to use the same directory as the ImportFromFile but the ImportFromStream doesn't have a path... hmm...  maybe I add a HighlighterDirectory property... if the value does not start with a drive, then the application path is used before the property value...

**Comment by EricGrange** [comment]
Yes, I know, I was already testing it for that usage (HTML with mixed DWS
scripts).
However the directory is not the only point, it's also being able to load
from resources that are not files, but bundled in the exe, obtained from a
db, etc. A callback based on streams would solve that, a HilighterDirectory
would not.

On Wednesday, May 13, 2015, Lasse Rautiainen <notifications@github.com>
wrote:
> Perhaps I need to explain what that range ParseFromFile is all about. It
makes possible to include multiple highlighters into a highlighter. See for
example "HTML with Scripts.json" and search "IncludeRange".
>
> I have totally forgotten the hard-coded path since I was testing this
feature. Well, it would be easy to use the same directory as the
ImportFromFile but the ImportFromStream doesn't have a path... hmm... maybe
I add a HighlighterDirectory property... if the value does not start with a
drive, then the application path is used before the property value...
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci4.googleusercontent.com/proxy/EuvFCIFzbVHGZNL4Hs0uI_AYTtjm2UVfWXkzFvtD4BbBKpQDhBuvcGksX_p5L4gWULD3nrK0gqH33BKwtMHUylAZst4Y3WwmCbPY3t-QjAN3mr5jUdVpk8nkGwSWxRTstDLzMxT08y-cMMoIJKQlHx33wRIr4w=s0-d-e1-ft#https://github.com/notifications/beacon/ACGG2kRdsXU3l3-0uC76ehdVX5sXtjdzks5oI83vgaJpZM4EZTBo.gif
>

**Comment by bonecode** [comment]
Fixed. There is now virtual CreateHighlighterIncludeFileStream function in the TBCEditorBase class. I also refactored JSON importer.
