### ISSUE TITLE
TBCEditorDemo.Forms.Main.pas(405): E2001 Ordinal type required

### ISSUE THREAD

**Issue by ThomasJaeger** [bonecode/TBCEditor#546]
Ok, now I'm getting this error when trying to compile the demo source:

[dcc32 Error] TBCEditorDemo.Forms.Main.pas(405): E2001 Ordinal type required

This is at line:

ObjectInspector.AddUnlistedProperties(['Ctl3D', 'CustomHint', 'Hint', 'HelpContext', 'HelpKeyword', 'HelpType',
'ImeMode', 'ImeName', 'ParentColor', 'ParentCtl3D', 'ParentCustomHint', 'ParentFont', 'ParentShowHint', 'ShowHint']);

**Comment by bonecode** [comment]
Delphi XE4? I can't repeat with the latest source.

**Comment by bonecode** [comment]
Fixed. But this is a total waste of time. I will remove that fix and also eventually XE4 packages from BCComponents, BCControls, and Common. I am always using the latest Delphi version and because those packages are for my personal use I don't care other versions. If someone want to use them, they can fix it by themselves.
